import type { CodegenConfig } from '@graphql-codegen/cli';

const schemaUrl = 'http://localhost:4000/graphql';

const warning = `
/**
 *  ⚠️ DO NOT EDIT ⚠️
 *  This file is automatically generated, run "yarn codegen" to update
 */
`;

const config: CodegenConfig = {
  overwrite: true,
  generates: {
    'src/types/__generated__/gql.types.ts': {
      schema: schemaUrl,
      plugins: [
        {
          add: {
            content: warning
          }
        },
        {
          typescript: {
            scalars: {
              Object: 'object',
              Any: 'any'
            }
          }
        }
      ]
    },
    'src/types/__generated__/gqlHelpers.types.ts': {
      schema: schemaUrl,
      plugins: [{ add: { content: warning } }, 'typescript-apollo-client-helpers']
    },
    src: {
      schema: schemaUrl,
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'types/__generated__/gql.types.ts',
        extension: '.types.ts',
        folder: '../types/__generated__'
      },
      plugins: [{ add: { content: warning } }, 'typescript-operations'],
      documents: [`src/api/**/*gql.ts`]
    }
  },
  hooks: {
    afterAllFileWrite: 'eslint --fix'
  }
};

export default config;
